N1 Rosalem/Controllers/BebidasController.cs
using Microsoft.AspNetCore.Mvc;
using BarApp.Models;
using System.Linq;
using BarApp.Data;
using N1_Rosalem.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using N1_Rosalem.Models;
using N1_Rosalem.Services;
using Microsoft.EntityFrameworkCore;


namespace BarApp.Controllers
{
    public class BebidasController : Controller
    {
        private readonly BarContext _context;
        private readonly MappingService _mappingService;

        public BebidasController(BarContext context, MappingService mappingService)
        {
            _context = context;
            _mappingService = mappingService;


        }

        // GET: Bebidas
        public IActionResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";
            ViewBag.CurrentFilter = searchString;

            var bebidas = from b in _context.Bebida
                          select b;

            if (!String.IsNullOrEmpty(searchString))
            {
                bebidas = bebidas.Where(b => b.Nome.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    bebidas = bebidas.OrderByDescending(b => b.Nome);
                    break;
                case "Price":
                    bebidas = bebidas.OrderBy(b => b.Preco);
                    break;
                case "price_desc":
                    bebidas = bebidas.OrderByDescending(b => b.Preco);
                    break;
                default:
                    bebidas = bebidas.OrderBy(b => b.Nome);
                    break;
            }

            var bebidaViewModels = bebidas.Select(b => _mappingService.MapToBebidaViewModel(b)).ToList();
            return View(bebidaViewModels);
        }


        // GET: Bebidas/Create
        [AdminOnly]
        public IActionResult Criar()
        {
            ViewBag.Origens = new SelectList(_context.Origem.ToList(), "Id", "origem");
            ViewBag.Receitas = new SelectList(_context.Receita.ToList(), "Id", "receita");
            return View();
        }


        // POST: Bebidas/Create
        [AdminOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Criar([Bind("Nome,Preco,Estoque,Descricao,ImagemURL,OrigemId,ReceitaId")] Bebida bebida)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bebida);
                _context.SaveChanges();
                var bebidas = _context.Bebida.ToList();
                var bebidaViewModels = bebidas.Select(b => _mappingService.MapToBebidaViewModel(b)).ToList();
                return PartialView("_BebidasPartial", bebidaViewModels);
            }

            ViewBag.Origens = new SelectList(_context.Origem.ToList(), "Id", "origem", bebida.OrigemId);
            ViewBag.Receitas = new SelectList(_context.Receita.ToList(), "Id", "receita", bebida.ReceitaId);
            return View(bebida);
        }


        // GET: Bebidas/Edit/5
        [AdminOnly]
        public IActionResult Edit(int id)
        {
            var bebida = _context.Bebida.Find(id);
            if (bebida == null)
            {
                return NotFound();
            }

            ViewBag.Origens = new SelectList(_context.Origem.ToList(), "Id", "origem", bebida.OrigemId);
            ViewBag.Receitas = new SelectList(_context.Receita.ToList(), "Id", "receita", bebida.ReceitaId);
            return View(bebida);
        }


        // POST: Bebidas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminOnly]
        public IActionResult Edit(int id, [Bind("Id,Nome,Preco,Estoque,Descricao,ImagemURL,OrigemId,ReceitaId")] Bebida bebida)
        {
            if (id != bebida.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bebida);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Bebida.Any(e => e.Id == bebida.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Origens = new SelectList(_context.Origem.ToList(), "Id", "origem", bebida.OrigemId);
            ViewBag.Receitas = new SelectList(_context.Receita.ToList(), "Id", "receita", bebida.ReceitaId);
            return View(bebida);
        }


        // GET: Bebidas/Details/5
        public IActionResult Details(int id)
        {
            var bebida = _context.Bebida
                .Include(b => b.Origem)
                .Include(b => b.Receita)
                .FirstOrDefault(m => m.Id == id);

            if (bebida == null)
            {
                return NotFound();
            }

            var bebidaViewModel = _mappingService.MapToBebidaViewModel(bebida);
            return View(bebidaViewModel);
        }



        // POST: Bebidas/Delete/5
        [AdminOnly]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var bebida = _context.Bebida.Find(id);
            if (bebida != null)
            {
                _context.Bebida.Remove(bebida);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult BebidasPartial(string sortOrder, string searchString)
        {
            // Lógica para filtrar e classificar as bebidas
            var bebidasFiltradas = from b in _context.Bebida
                                   select b;

            if (!String.IsNullOrEmpty(searchString))
            {
                bebidasFiltradas = bebidasFiltradas.Where(b => b.Nome.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    bebidasFiltradas = bebidasFiltradas.OrderByDescending(b => b.Nome);
                    break;
                case "Price":
                    bebidasFiltradas = bebidasFiltradas.OrderBy(b => b.Preco);
                    break;
                case "price_desc":
                    bebidasFiltradas = bebidasFiltradas.OrderByDescending(b => b.Preco);
                    break;
                default:
                    bebidasFiltradas = bebidasFiltradas.OrderBy(b => b.Nome);
                    break;
            }

            return PartialView("_BebidasPartial", bebidasFiltradas.ToList());
        }
    }
}

N1 Rosalem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - N1_Rosalem</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/N1_Rosalem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">N1_Rosalem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @if (User.HasClaim(c => c.Type == "IsAdmin" && c.Value == "True"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Bebidas" asp-action="Index">Área Restrita</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Sobre</a>
                            </li>
                            <li class="nav-item">
                                <form id="logoutForm" asp-area="" asp-controller="Login" asp-action="Logout" method="post">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Register">Registrar</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>